# Generated by Django 3.0.5 on 2020-04-19 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='course',
            field=models.CharField(max_length=50),
        ),
    ]
